const contractAddress = "0xF73AB7b474485f4401F9EdD8B9d0C8404d1e6D09"; // Replace with your own contract address
const chain = 'goerli'; // goerli, polygon, or ethereum

const welcome_h1 = "Bienvenido a Digital Magic Dragons";
const welcome_h2 = "Conectate a MetaMask Para comenzar";
const welcome_p = 'Digital Magic Dragons';
const h1_presale_coming_soon = "NFT Drop Proximamente!!";
const h1_presale_mint = "Pre-venta Pública abierta!!";
const h1_public_mint = "Minteo Público abierto!!";
const h2_presale_coming_soon = "Proximamente!";
const h2_presale_mint = "Tiempo para la pre-venta";
const p_presale_coming_soon = "Estamos trabajando para que tengas la mejor colección NFT. Mantente informado para las actualizaciones!";
const p_presale_mint_not_whitelisted = "No estás en la whitelist para la pre-venta... 😢";
const p_presale_mint_whitelisted = "Ya estás en la whitelist para la pre-venta! 🎉";
const p_presale_mint_already_minted = "Ta solicitastea acceso a la whitelist. Gracias! 🎉";
const p_public_mint = "El Minteo está abierto para todo público. 🎉";
const button_presale_coming_soon = "Acceder a la Whitelist";
const button_presale_mint_whitelisted = "Mintea tu NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Únete a la comunidad";
const button_public_mint = "Mintea tu NFT";
const mint_failed = "Mintea fallida. 😢 Intenta de nuevo por favor.";
